"""Generate assets/maps/urban.map: two city complexes joined by a highway.

The highway is ~2000 world units, which at GTJ3D's 11 units per metre is about
180 m of open road -- long enough to get a car to its top speed, run out of
road and have to brake, which is the point of it. Traffic patrols it in both
directions via the `aicar` command.

  python tools/make_urban.py
"""
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "maps", "urban.map")

SIZE_X, SIZE_Z = 5600, 2400
WEST_END = 1700           # west complex spans x 0 .. WEST_END
EAST_START = 3900         # east complex spans EAST_START .. SIZE_X
ROAD_Z0, ROAD_Z1 = 1000, 1400   # the carriageways

rng = random.Random(20260809)
L = []


def w(s=""):
    L.append(s)


def block(x, z, sx, sz, h, tex, tile=64):
    w(f"box {x} 0 {z} {sx} {h} {sz} {tex} {tile}")


def complex_at(ox, name):
    """A city block: towers, a walled yard, crate cover and a plaza."""
    w(f"# ---------------------------------------------- {name}")
    texes = ["brick", "wall_a", "wall_b", "wall_d", "concrete", "stone"]
    # Four towers, one per quadrant, with a gap between them for streets.
    for i, (dx, dz) in enumerate(((160, 160), (1060, 160),
                                  (160, 1560), (1060, 1560))):
        h = rng.choice((110, 130, 160, 190))
        block(ox + dx, dz, 470, 470, h, rng.choice(texes))
    # Enterable tower on the middle of the block.
    w(f"building {ox + 700} 1000 330 330 0 5 46 concrete stone2")
    # Yard walls with gaps, for cover off the main road.
    w(f"wall {ox + 120} 900 {ox + 560} 900 0 130 42 metal 48")
    w(f"wall {ox + 700} 900 {ox + 1420} 900 0 130 42 metal 48")
    w(f"wall {ox + 120} 1500 {ox + 560} 1500 0 130 42 metal 48")
    w(f"wall {ox + 1150} 1500 {ox + 1420} 1500 0 130 42 metal 48")
    # Crate cover and props.
    for i in range(9):
        cx = ox + rng.randrange(140, 1400, 20)
        cz = rng.randrange(120, 2200, 20)
        if ROAD_Z0 - 90 < cz < ROAD_Z1 + 90:
            continue                       # keep the carriageways clear
        block(cx, cz, 56, 56, 56, rng.choice(("crate", "crate2")), 56)
    # A ramp onto the low roofs.
    w(f"stairs {ox + 600} 300 90 300 0 108 2 20 metal")
    block(ox + 560, 250, 130, 60, 108, "metal", 32)
    w()


w("# ============================================================================")
w("#  Kaj's Shooter Game 3D  --  \"Urban Complex\"")
w("#")
w("#  Two city complexes at either end, joined by a highway about 180 m long")
w("#  (2000 world units at GTJ3D's 11 units per metre) with traffic running")
w("#  both ways on it. Long enough to wind a car right out and still need to")
w("#  brake for the far end.")
w("#")
w("#  Generated by tools/make_urban.py -- regenerate rather than hand-editing.")
w("# ============================================================================")
w()
w("name Urban Complex")
w(f"size {SIZE_X} {SIZE_Z}")
w("ground floor 64")
w("fog 30 46 54 900 4200")
w("sky 26 34 42")
w()
w("# ---------------------------------------------------------------- perimeter")
w(f"wall 0 0 {SIZE_X} 0 0 240 70 brick 64")
w(f"wall 0 {SIZE_Z} {SIZE_X} {SIZE_Z} 0 240 70 brick 64")
w(f"wall 0 0 0 {SIZE_Z} 0 240 70 brick 64")
w(f"wall {SIZE_X} 0 {SIZE_X} {SIZE_Z} 0 240 70 brick 64")
w()

complex_at(0, "WEST COMPLEX")
complex_at(EAST_START, "EAST COMPLEX")

w("# ------------------------------------------------------------------- highway")
w("# Two carriageways with a central reservation, crash barriers either side,")
w("# and open ground beyond them so a car that leaves the road keeps going.")
road_len = EAST_START - WEST_END
w(f"box {WEST_END} 0 {ROAD_Z0} {road_len} 3 {ROAD_Z1 - ROAD_Z0} stone2 96")
# central reservation
w(f"box {WEST_END} 0 {(ROAD_Z0 + ROAD_Z1) // 2 - 12} {road_len} 16 24 stone 48")
# crash barriers, broken into runs so there are gaps to get on and off
seg = road_len // 7
for i in range(7):
    if i in (2, 5):
        continue
    x = WEST_END + i * seg
    w(f"box {x} 0 {ROAD_Z0 - 26} {seg - 30} 20 14 metal 32")
    w(f"box {x} 0 {ROAD_Z1 + 12} {seg - 30} 20 14 metal 32")
# overpass halfway, so there is something to drive under and fight on
mid = (WEST_END + EAST_START) // 2
w(f"box {mid - 60} 150 {ROAD_Z0 - 320} 120 20 {(ROAD_Z1 - ROAD_Z0) + 640} "
  f"stone2 64")
w(f"box {mid - 80} 0 {ROAD_Z0 - 340} 40 150 40 pillar 40")
w(f"box {mid + 40} 0 {ROAD_Z0 - 340} 40 150 40 pillar 40")
w(f"box {mid - 80} 0 {ROAD_Z1 + 300} 40 150 40 pillar 40")
w(f"box {mid + 40} 0 {ROAD_Z1 + 300} 40 150 40 pillar 40")
w(f"stairs {mid - 60} {ROAD_Z0 - 560} 120 200 0 150 2 26 metal")
w()

w("# ------------------------------------------------------------------- traffic")
w("# aicar <x1> <z1> <x2> <z2> <y> <kind> <r> <g> <b>")
w("#   drives back and forth between the two points; get in one with E and it")
w("#   becomes yours. kind 0 saloon, 1 van, 3 supercar.")
lane_w = (ROAD_Z0 + ROAD_Z1) // 2 - 60      # westbound lane centre
lane_e = (ROAD_Z0 + ROAD_Z1) // 2 + 60      # eastbound lane centre
paints = [(150, 34, 30), (28, 52, 120), (196, 190, 178), (30, 30, 34),
          (150, 128, 40), (40, 104, 82), (110, 42, 110), (200, 200, 205)]
for i in range(6):
    t = i / 5.0
    x = int(WEST_END + 120 + t * (road_len - 240))
    r, g, b = paints[i % len(paints)]
    kind = 3 if i == 2 else (1 if i == 4 else 0)
    w(f"aicar {x} {lane_e} {EAST_START - 120} {lane_e} 0 {kind} {r} {g} {b}")
for i in range(6):
    t = i / 5.0
    x = int(EAST_START - 120 - t * (road_len - 240))
    r, g, b = paints[(i + 3) % len(paints)]
    kind = 3 if i == 1 else 0
    w(f"aicar {x} {lane_w} {WEST_END + 120} {lane_w} 0 {kind} {r} {g} {b}")
w()

w("# ------------------------------------------------------------- parked & armour")
w("car 300 700 0 0 0 150 34 30")
w("car 420 700 0 0 3 235 232 226")
w("car 1200 1900 0 2 1 40 44 40")
w(f"car {EAST_START + 300} 700 0 0 0 28 52 120")
w(f"car {EAST_START + 420} 700 0 0 3 236 190 40")
w(f"car {EAST_START + 1200} 1900 0 2 0 196 190 178")
w("tank 900 1800 0 0 92 98 74")
w(f"tank {EAST_START + 900} 1800 0 2 70 76 58")
w()

w("# ---------------------------------------------------------------------- spawns")
for x, z, yaw in ((120, 300, 0), (120, 2100, 0), (1500, 300, 270),
                  (1500, 2100, 90), (900, 1200, 0),
                  (EAST_START + 1400, 300, 180),
                  (EAST_START + 1400, 2100, 180),
                  (EAST_START + 200, 300, 90),
                  (EAST_START + 200, 2100, 270),
                  (EAST_START + 800, 1200, 180),
                  (mid, ROAD_Z0 - 700, 0), (mid, ROAD_Z1 + 700, 180)):
    w(f"spawn {x} 4 {z} {yaw}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print(f"wrote {OUT}  ({len(L)} lines)")
